### ISSUE TITLE
Purchases

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#18]
## Description
Everything is restricted to BOARD users. Technically, we want a purchase to reference a single good. Whereas, a user will think of a purchase as many such rows in a database with the same date from the same supplier. That is, there is some abuse of language when we say "registering a purchase creates many in db."

## Tasks
- [x] Register purchase
  - [x] Purchase model ("subclass" of Good)
  - [x] Create many
  - [x] Registration form page

- [x] Find purchases
  - [x] Query a purchase, many purchases in a period, all purchases
  - [x] Purchases page
  - [x] Pagination
  - [x] Details of a purchase (display the individual rows in the db)

- [x] Update purchases
  - [x] Reuse the registration page
  - [x] Update many

- [x] Delete purchase(s), e.g. by button and confirmation in purchases page
