### ISSUE TITLE
Sales

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#19]
## Description
Everything is restricted to BOARD users. Technically, we want a sale to reference a single good. Whereas, a user will think of a sale as many such rows in a database with the same date. That is, there is some abuse of language when we say "registering a sale creates many in db."

## Tasks
- [x] Register sale
  - [x] Sale model ("subclass" of Good)
  - [x] Create many
  - [x] Registration form page

- [x] Find sales
  - [x] Query a sale, many sales in a period, all sales
  - [x] Sales page
  - [x] Pagination
  - [x] Details of a sale (display the individual rows in the db)

- [x] Update sales
  - [x] Reuse the registration page
  - [x] Update many

- [x] Delete sale(s), e.g. by button and confirmation in sales page
