### ISSUE TITLE
Item count

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#20]
## Description
Everything is restricted authenticated users, unless specified. Technically, we want an item count to reference a single good. Whereas, a user will think of an item count as many such rows in a database with the same date. That is, there is some abuse of language when we say "registering an item count creates many in db."

## Tasks
- [ ] Register item count
  - [ ] ItemCount model ("subclass" of Good)
  - [ ] Create many
  - [ ] Registration form page

- [ ] Find item counts
  - [ ] Query an item count, many item counts in a period, all item counts (board only)
  - [ ] Query item counts by user
  - [ ] Item counts page
  - [ ] Pagination
  - [ ] Details of a item count (display the individual rows in the db)

- [ ] Update item count
  - [ ] Create negative version, and mark both as void. Create new item count with updated values.
  - [ ] Reuse the registration page

- [ ] Delete item count(s), e.g. by button and confirmation in item count page. Use same method as updating.
