### ISSUE TITLE
Cost of goods sold (COGS)

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#21]
## Description
Everything is restricted BOARD users. COGS is a report using the FIFO method to compute the cost (value of the used goods) in a period. The report is meant to be an accounting document created each month, so there must be a printing button. It will also be a good tool to compare revenues and costs for goods, and keeping track of the inventory.

## Note
Depending on performance, we might denormalize (either hybridlike, updating COGS report once a new purchase, sale, or item count is registered, or manually). 

## Tasks
- [ ] FIFO method for a single good
- [ ] Determine accumulated, used and remaining inventory for a single good for a month
- [ ] Compute costs and wasted units for a month
  - [ ] Use FIFO method, and find the ingoing and outgoing inventories
  - [ ] Display report, and print with date
