### ISSUE TITLE
Good, more functionality

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#28]
## Description
Everything is restricted to BOARD users. In PR #27, we introduced the reports page and we would like a similar page for a single good, only here we want to query both purchases and sales (for a single good). For accounting purposes, we will only allow a good to be deleted or updated if there are no relations to the good (i.e. it has never been used in a sale, purchase or otherwise).

## Tasks
- [ ] Goods page
  - [ ] Pagination

- [ ] Good report page
  - [ ] Query all purchases and sales in a given period for a single good

- [ ] Delete and update good (ONLY IF there are no relations to the good)
