### ISSUE TITLE
Supplier, more functionality

### ISSUE THREAD

**Issue by EvenAsl** [realfagskjelleren/realfagskjelleren.no#29]
## Description
Everything is restricted to BOARD users. In PR #27, we introduced the reports page and we would like a similar page for a single supplier, only here we want to query both purchases and sales (for a single supplier). For accounting purposes, we will only allow a supplier to be deleted or updated if there are no relations to the supplier (i.e. it has never been used in a purchase or otherwise).

## Tasks
- [ ] Suppliers page
  - [ ] Pagination

- [ ] Supplier report page
  - [ ] Query all purchases in a given period for a single supplier

- [ ] Delete and update supplier (ONLY IF there are no relations to the supplier)
